### ISSUE TITLE
java.lang.NoSuchFieldError: No static field hide_in_inspector_tag

### ISSUE THREAD

**Issue by ismai117** [MatkovIvan/nav_cupcake#3]
I'm receiving this error when I try to navigate on an Android device. 

java.lang.NoSuchFieldError: No static field hide_in_inspector_tag of type I in class Landroidx/compose/ui/R$id; or its superclasses (declaration of 'androidx.compose.ui.R$id' appears in /data/app/~~NK3-mfmkyNUJ2km7H1Ov3g==/org.ncgroup.droidjobskmp-cFM_FPLbDI5YzIIeBxWxdA==/base.apk!classes15.dex)
                                                                                                    	at androidx.compose.material.ripple.RippleContainer.<init>(RippleContainer.android.kt:70)
                                                                                                    	at androidx.compose.material.ripple.AndroidRippleIndicationInstance.getOrCreateRippleContainer(Ripple.android.kt:255)
                                                                                                    	at androidx.compose.material.ripple.AndroidRippleIndicationInstance.addRipple(Ripple.android.kt:198)
                                                                                                    	at androidx.compose.material.ripple.Ripple$rememberUpdatedInstance$1$1.emit(Ripple.kt:138)
                                                                                                    	at androidx.compose.material.ripple.Ripple$rememberUpdatedInstance$1$1.emit(Ripple.kt:136)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
                                                                                                    	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
                                                                                                    	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by MatkovIvan** [comment]
Cannot reproduce it on this project (both emulator and real device).
Did you add some other dependencies? It looks similar to https://stackoverflow.com/questions/78248205/
Please note that on Android it uses original Google's binaries, but a recent alpha release, not a stable one. I suggest that you try to reproduce it in an Android-only project and create a report in Google issue tracker.

**Comment by ismai117** [comment]
adding "androidx.compose.material:material-ripple:1.7.0-alpha05" fixed it, thanks!
